name: Deploy to QA

on:
  push:
    branches:
      - release

jobs:
  deploy-to-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Build Docker Image
        run: docker build -t ecomarket-servicio-resenias:qa .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: docker tag ecomarket-servicio-resenias:qa ${{ secrets.DOCKERHUB_USERNAME }}/ecomarket-servicio-resenias:qa

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecomarket-servicio-resenias:qa

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Run Deployment Script on QA Server
        run: |
          sshpass -p "${{ secrets.QA_SERVER_PASSWORD }}" ssh -p ${{ secrets.QA_SERVER_PORT }} -o StrictHostKeyChecking=no ${{ secrets.QA_SERVER_USER }}@${{ secrets.QA_SERVER_HOST }} "/home/estudiante/ecomarket-app-backend-dotnet/scripts/QA/deploy_docker_image-ecomarket-servicio-resenias-qa.sh"
